Models/Catergory.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FoodCatergoryWeb.Models;

public class Catergory
{
    [Key]
    public int Id { get; set; }
    [Required]
    public string? Name { get; set; }
    [DisplayName("Display")]
    [Range(1,100,ErrorMessage ="Display Order Must Be Between 1 and 100 only")]
    public int Display { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;

}

Models/ErrorViewModel.cs
namespace FoodCatergoryWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CatergoryController.cs
using FoodCatergoryWeb.Data;
using FoodCatergoryWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FoodCatergoryWeb.Controllers;

public class CatergoryController : Controller
{
    private readonly ApplicationDbContext _db;

    public CatergoryController(ApplicationDbContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        IEnumerable<Catergory> objCategoryList = _db.Catergories;
        return View(objCategoryList);
    }
    //GET
    public IActionResult Create()
    {
        
        return View();
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Catergory obj)
    {   if(obj.Name == obj.Display.ToString())
        {
            ModelState.AddModelError("name", "The Display Order cannot exactly match the name");
        }
        if (ModelState.IsValid)
        {
            _db.Catergories.Add(obj);
            _db.SaveChanges();
            TempData["success"] = "Catergory created successfuly";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    //GET
    public IActionResult Edit(int? id)
    {
        if(id == null || id == 0)
        {
            return NotFound();
        }
        var CatergoryFromDb = _db.Catergories.Find(id);

        if(CatergoryFromDb == null)
        {
            return NotFound();
        }
        return View(CatergoryFromDb);
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]

    public IActionResult Edit(Catergory obj)
    {
        if (obj.Name == obj.Display.ToString())
        {
            ModelState.AddModelError("name", "The Display Order cannot exactly match the name");
        }
        if (ModelState.IsValid)
        {
            _db.Catergories.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "Catergory updated successfuly";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    //GET
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var CatergoryFromDb = _db.Catergories.Find(id);

        if (CatergoryFromDb == null)
        {
            return NotFound();
        }
        return View(CatergoryFromDb);
    }
    //POST
    [HttpPost,ActionName("Delete")]
    [ValidateAntiForgeryToken]

    public IActionResult DeletePOST(int? id)
    {
        var obj = _db.Catergories.Find(id);
        if (obj == null)
        {
            return NotFound();
        }
        _db.Catergories.Remove(obj);
        _db.SaveChanges();
        TempData["success"] = "Catergory Deleted successfuly";
        return RedirectToAction("Index");

    }

}

Controllers/HomeController.cs
using FoodCatergoryWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FoodCatergoryWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Catergory/Create.cshtml
@model Catergory

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Catergory</h2>
        <hr />
        </div>
        
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Display"></label>
            <input asp-for="Display" class="form-control"/>
            <span asp-validation-for="Display" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Catergory" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Catergory/Delete.cshtml
@model Catergory

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Catergory</h2>
        <hr />
        </div>
        
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Display"></label>
            <input asp-for="Display" disabled class="form-control"/>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Catergory" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

Views/Catergory/Edit.cshtml
@model Catergory

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Update Catergory</h2>
        <hr />
        </div>
        
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Display"></label>
            <input asp-for="Display" class="form-control"/>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Catergory" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Catergory/Index.cshtml
@model IEnumerable<Catergory>
@{
    ViewData["Title"] = "Index";
}


<div class="container  p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Catergory List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Catergory" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Catergory
            </a>
        </div>
    </div>
    <br /><br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Catergory Name
            </th>
            <th>
                Display Order
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
                </td>
                <td width="30%">
                    @obj.Display
                </td>
                <td>
                    <div class="m-75 btn-group" role="group">
                            <a asp-controller="Catergory" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                    <div class="m-75 btn-group" role="group">
                            <a asp-controller="Catergory" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodCatergoryWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodCatergoryWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Catergory" asp-action="Index">Catergory</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodCatergoryWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            
                        </li>
                        <li class="nav-item">
                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-mute bg-dark">
        <div class="container">
            &copy; 2023 - FoodCatergoryWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}